FROM debian:latest
RUN apt-get update && apt-get install python3-pip -y && pip3 install Flask && pip3 install Flask-Pydantic && pip3 install pymongo && pip3 install numpy && pip3 install mysql-connector-python
ADD API_SQL.py /src/apiSql.py
ADD tools.py /src/tools.py
WORKDIR /src/
EXPOSE 5002
VOLUME ./config:/src/config
CMD python3 apiSql.py
